name: Terraform Integration

on:
  push:
    branches:
      - terraform

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    environment: dev
    steps:
 # Checkout the repository to the GitHub Actions runner
      - name: Checkout Repo
        uses: actions/checkout@v1

 # Install the preferred version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        id:   init
        env:
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID}}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET}}
        working-directory: 'terraform/core/env_vars'
        if: github.event_name == 'pull_request'
        run:
          terraform init -backend-config=config/uday_backend.conf


      - name: Terraform Format
        run:  terraform fmt -check

      - name: Terraform Apply
        id:   apply
        env:
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID}}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET}}
        working-directory: 'terraform/core/env_vars'
        if: github.event_name == 'pull_request'
        run:
          terraform apply -var-file=uday.tfvars -auto-approve -lock=false
