name: Change Branches
  
env:
  SSH_USER: ${{ secrets.DEPLOY_USER }}
  SSH_KEY: ${{ secrets.DEPLOY_KEY }}
  Devops_HOST: 10.241.xxx.xxx


on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Server
        options: 
       
        - Devops VM
      
      message:
        required: true

jobs:
 deployment:
    
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}

      - name: Update Config File
        run: |
          mkdir -p ~/.ssh/
          rm ~/.ssh/config
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END

          Host Devops_HOST
            HostName $Devops_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no

          END

      - name: Devops SSH
        run: |
          ssh Devops_HOST 'cd /home/services/persostack/ && git checkout ${{ steps.vars.outputs.short_ref }} && git pull'
        if: ${{ github.event.inputs.name == 'Devops VM' }}

    

      
